#!/usr/bin/env bash
# ===========================================================================
# docker/enable_mqtts.sh — enable MQTTS (TLS) on the Mosquitto broker.
#
# One-shot, idempotent helper that runs ON the VPS. It provisions the
# Let's Encrypt certificate into a directory the Mosquitto container can
# read, recreates the broker so it picks up the 8883 listener + cert mount
# already present in docker/mosquitto.conf and docker-compose.prod.yml,
# installs a certbot renewal hook so future renewals keep the broker's cert
# fresh, and verifies the TLS handshake.
#
# Usage (as root):
#   sudo sh docker/enable_mqtts.sh
#
# Env overrides:
#   MQTT_DOMAIN    domain to serve (default: retail-vantag.com)
#   CERT_SRC       certbot live dir (default: /etc/letsencrypt/live/$MQTT_DOMAIN)
#   COMPOSE_FILE   compose file      (default: docker/docker-compose.prod.yml)
# ===========================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOMAIN="${MQTT_DOMAIN:-retail-vantag.com}"
CERT_SRC="${CERT_SRC:-/etc/letsencrypt/live/${DOMAIN}}"
CERT_DST="/opt/vantag/mqtt-certs"
COMPOSE_FILE="${COMPOSE_FILE:-docker/docker-compose.prod.yml}"
BROKER_UID=1883
CONTAINER="${MOSQUITTO_CONTAINER:-vantag-mosquitto-prod}"

info()  { echo "[enable_mqtts] $*"; }
fail()  { echo "[enable_mqtts] ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || fail "run as root: sudo sh docker/enable_mqtts.sh"
cd "$REPO_ROOT"

# ── 1. Certificate source present? ────────────────────────────────────────
[ -f "${CERT_SRC}/fullchain.pem" ] || fail "missing ${CERT_SRC}/fullchain.pem — run certbot first for ${DOMAIN}"
[ -f "${CERT_SRC}/privkey.pem" ]  || fail "missing ${CERT_SRC}/privkey.pem — run certbot first for ${DOMAIN}"

# ── 2. Provision certs into a broker-readable directory (idempotent) ──────
mkdir -p "$CERT_DST"
cp -Lf "${CERT_SRC}/fullchain.pem" "${CERT_DST}/fullchain.pem"
cp -Lf "${CERT_SRC}/privkey.pem"  "${CERT_DST}/privkey.pem"
chown -R "${BROKER_UID}:${BROKER_UID}" "$CERT_DST"
chmod 640 "${CERT_DST}/fullchain.pem" "${CERT_DST}/privkey.pem"
info "certificates provisioned into ${CERT_DST}"

# ── 3. Confirm the repo config is enabled ────────────────────────────────
grep -q '^listener 8883' docker/mosquitto.conf \
  || fail "docker/mosquitto.conf has no active 'listener 8883' — git pull the latest config first"
grep -q '/mosquitto/certs:ro' "$COMPOSE_FILE" \
  || fail "${COMPOSE_FILE} does not mount ${CERT_DST} — git pull the latest config first"

# ── 4. Recreate the broker so it loads 8883 + the cert mount ──────────────
info "recreating mosquitto broker..."
docker compose -f "$COMPOSE_FILE" up -d --force-recreate mosquitto
sleep 4

state="$(docker inspect --format='{{.State.Status}}' "$CONTAINER" 2>/dev/null || echo missing)"
[ "$state" = "running" ] || { docker logs "$CONTAINER" --tail 40; fail "mosquitto container is not running (state=$state)"; }

docker logs "$CONTAINER" --tail 200 | grep -q 'listen socket on port 8883' \
  || { docker logs "$CONTAINER" --tail 40; fail "broker did not open port 8883 — check cert mount + mosquitto.conf"; }
info "broker listening on 8883"

# ── 5. Verify the TLS handshake end-to-end ────────────────────────────────
echo | openssl s_client -connect "${DOMAIN}:8883" -servername "${DOMAIN}" 2>/dev/null \
  | openssl x509 -noout -subject -dates \
  || fail "TLS handshake on ${DOMAIN}:8883 failed (is 8883 open in the firewall?)"
info "TLS handshake OK on ${DOMAIN}:8883"

# ── 6. Install certbot renewal deploy hook (idempotent) ───────────────────
HOOK_DIR="/etc/letsencrypt/renewal-hooks/deploy"
HOOK="${HOOK_DIR}/vantag-mqtt-certs.sh"
mkdir -p "$HOOK_DIR"
cat > "$HOOK" <<EOF
#!/bin/sh
# Auto-generated by docker/enable_mqtts.sh — copy renewed certs into the
# broker's cert dir and restart Mosquitto so MQTTS keeps working.
set -e
cp -Lf "${CERT_SRC}/fullchain.pem" "${CERT_DST}/fullchain.pem"
cp -Lf "${CERT_SRC}/privkey.pem"  "${CERT_DST}/privkey.pem"
chown -R "${BROKER_UID}:${BROKER_UID}" "${CERT_DST}"
chmod 640 "${CERT_DST}/fullchain.pem" "${CERT_DST}/privkey.pem"
docker restart "$CONTAINER" >/dev/null
EOF
chmod +x "$HOOK"
info "renewal hook installed: ${HOOK}"

info ""
info "============================================================"
info " MQTTS enabled and verified on ${DOMAIN}:8883"
info ""
info " Next steps:"
info "   1. Re-download an Edge Agent and confirm a Test unlock."
info "   2. Lock down plaintext 1883/9001 (bind to 127.0.0.1 in"
info "      docker-compose.prod.yml) and open 8883/tcp in ufw."
info "   3. Commit this config so git-reset deploys keep it."
info "============================================================"
